spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/indianroadmap_recommendations

indianroadmap:
  services:
    destination:
      base-url: http://localhost:8081
    story:
      base-url: http://localhost:8083

logging:
  level:
    com.indianroadmap: DEBUG
